### ISSUE TITLE
ArrayBuffer not producing same md5 as binary string

### ISSUE THREAD

**Issue by nolanlawson** [satazor/SparkMD5#21]
This seems to be related to the incremental interface, because I cannot reproduce this bug when I try to do an md5 hash all at once.

I don't have a small reproducible test case yet for you, but if you check out the https://github.com/pouchdb/pouchdb/pull/3379 branch and run

```
npm install
npm run dev
```

then load [this link](http://localhost:8000/tests/integration/?grep=test.attachments.js-local%20putAttachment%20and%20getAttachment%20with%20big%20png%20data) in a browser, then you will see the failure.

Sorry for a lack of details; I will try to delve deeper unless you would like to investigate it yourself. (I'm a bit busy at the moment, but I thought it was prudent to let you know about this bug.)

**Comment by nolanlawson** [comment]
Bah, it turned out to be a bug in PouchDB. "Why do you only see the spec in your neighbor's eye..." ;)

**Comment by satazor** [comment]
No problem! Im still trying to find time to try pouchdb, keep up the great work.
