### ISSUE TITLE
Array returned for raw output

### ISSUE THREAD

**Issue by wingsergey** [satazor/SparkMD5#26]
I tried to use your awesome library to get raw result but got array with '1746531795,941883451,402336312,-1378573203'.

I expected for string 16 chars length. What I do wrong?

You can reproduce it on you examples from test directory. Just set second parameter to ``true`` as in instruction ``SparkMD5.hashBinary(e.target.result, true)`` .

How I can get raw binary string like in php function md5(str, true); ?

**Comment by satazor** [comment]
The second argument when set to `true` returns the raw (bytes) result. Remove it or set it to `false` to get a `hex` result.

**Comment by satazor** [comment]
Oh nvm, I have read the md5 documentation now and I understand your issue.

**Comment by wingsergey** [comment]
What you can advise to me? Can you implement such feature?

**Comment by satazor** [comment]
Yes I could implement such feature. Actually the correct way is to return a binary string instead of what is being returned now. I need some time to actually implement this because I'm currently very busy at work.

For now the fastest way for you is to do something like this:

```js
function hex2bin(hex) {
    var bytes = [],
        str;

    for (var i = 0; i < hex.length - 1; i += 2) {
        bytes.push(parseInt(hex.substr(i, 2), 16));
    }

    return String.fromCharCode.apply(String, bytes);
}

hex2bin(SparkMD5.hashBinary(yourstuff));
```

**Comment by wingsergey** [comment]
It helped. Thank you very much. You are genius.

**Comment by satazor** [comment]
Hehe, thanks for the compliment.

**Comment by satazor** [comment]
Version `2.0.0` now returns a binary string if `raw` is true, similar to other languages such as PHP. See: https://github.com/satazor/SparkMD5/commit/80acecd301a70f75f7ac76c3883442be05c33d8e
